version: '3.7'

services:
  go:
    container_name: go-workspace
    build:
      context: .
      target: dev
    volumes:
      - './:/work'
    stdin_open: true # docker run -i
    tty: true        # docker run -t