version: '3.7'

networks:
  backend:

services:
  go:
    container_name: web
    build:
      context: .
      # target: dev
    ports:
      - 8080:8080
    networks:
      - backend
    # volumes:
    #   - './:/work'
    # stdin_open: true # docker run -i
    # tty: true        # docker run -t
  mongo-express:
    container_name: mongodb
    image: mongo
    restart: always
    environment:
      - "MONGO_INITDB_DATABASE: mydb"
      - "MONGO_INITDB_ROOT_USENAME: root"
      - "MONGO_INITDB_ROOT_PASSWORD: rootpassword"
    ports:
      - 27017:27017
    networks:
      - backend
    # volumes:
    #   - mongodb_data_container:/data/db